data_root: ./datasets/CUB_200_2011_FewShot
image_size: 84
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1
workers: 6 # number of workers for dataloader in all threads
dataloader_num: 1
