includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/MCL.yaml

# classifier:
#   name: MCL
#   kwargs:
#     n_k: 3
#     katz_factor: 0.5
#     gamma: 20
#     gamma2: 10

# backbone:
#   name: Conv64F_MCL
#   kwargs: ~

# train_episode: 20000
# test_episode: 1000
# epoch: 30

# optimizer:
#   name: Adam
#   kwargs:
#     lr: 0.001
#     betas: [0.5, 0.9]
#   other: ~

# lr_scheduler:
#   name: StepLR
#   kwargs:
#     gamma: 0.1
#     step_size: 10

# way_num: 5
# shot_num: 1
# query_num: 15
# batch_size: 4

# test_way: 5
# test_shot: 1
# test_query: 15

classifier:
  name: MCL
  kwargs:
    n_k: 3
    katz_factor: 0.5
    gamma: 20
    gamma2: 10

pretrain_path: /root/autodl-tmp/MCL-master1/checkpoint/miniImagenet_FRN_pre/miniimagenet-e0_pre.pth

backbone:
  name: resnet12_mcl
  kwargs: ~

train_episode: 200
test_episode: 500
epoch: 40
optimizer:
  name: SGD
  kwargs:
    lr: 0.0005
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: True 
  other: ~

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 10

way_num: 5
shot_num: 1
query_num: 15
batch_size: 1

test_way: 5
test_shot: 1
test_query: 15
