includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml

way_num: 5
shot_num: 1
query_num: 15
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~

workers: 0
ensemble: True
ensemble_kwargs:
  name: quickboost
  need_train: True
  other:
    pretrained_encoder_path: './datasets/QuickBoost/embedding_resnet18_64classes.pkl'
    pretrained_encoder_test_path: './datasets/QuickBoost/embedding_resnet18_64classes_test.pkl'
    pretrained_module_name: ProtoNet-Conv64F
    # pretrained_module_path should contain the result files of the libfewshot training
    # as least contain: path/config.yaml, path/checkpoints/model_best.pth, path/checkpoints/emb_func_best.pth
    pretrained_module_path: './results/ProtoNet--Conv64F-5-1-Jul-18-2025-17-47-36/'
    # kwargs for sklearn random-forest
    seed: 0
    rf_kwargs:
      n_estimators: 200
      max_features: 20
      random_state: 0
